version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/python:3.8'  # CHANGE ME 1 - Replace with the appropriate Docker image for your stack
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: |
            # CHANGE ME 2 - Replace with the actual commands to install dependencies and build your project
            # Example for a Python project:
            # pip install -r requirements.txt
            # python setup.py install
            echo "Install your dependencies and build your project here"
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
