version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/python:3.8'  # If you still need Python, you can use this image
    steps:
      - checkout  # This checks out your code from GitHub
      - run:
          name: Install Node.js and npm
          command: |
            curl -fsSL https://deb.nodesource.com/setup_16.x | bash -  # Setup Node.js 16 (or use another version)
            sudo apt-get install -y nodejs
      - run:
          name: Install dependencies and build project
          command: |
            npm install  # Install the npm dependencies
      - sonarcloud/scan  # This step triggers the SonarCloud analysis

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0  # This is the orb that integrates SonarCloud into CircleCI

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud  # You can define additional contexts if needed

