version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/python:3.8'  # Replace with the appropriate Docker image for your project
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: ./gradlew build  # Modify this to your build command
      - run:
          name: Run SonarScanner
          command: |
            sonar-scanner \
              -Dsonar.projectKey=mybank_onlinebanking \
              -Dsonar.organization=mybankorg \
              -Dsonar.sources=.

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
           # You can define additional contexts if needed
