version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/python:3.8'  # Keep your original Docker image for Python 3.8 (adjust as needed)
    steps:
      - checkout  # This checks out your code from GitHub
      - run:
          name: Install dependencies and build project
          command: |
            # If you're using Python, make sure you're installing dependencies
            # Adjust as per your project needs
            echo "Installing dependencies"
             npm install # Assuming you're using a requirements file for Python dependencies
      - sonarcloud/scan  # This step triggers the SonarCloud analysis

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0  # This is the orb that integrates SonarCloud into CircleCI

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
  # You can define additional contexts if needed
