version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0  # SonarCloud orb

jobs:
  build-and-analyze:
    docker:
      - image: cimg/node:18.0  # Node.js for frontend
      - image: cimg/openjdk:17.0  # Java for backend
    steps:
      - checkout  # Check out code

      # Build Java backend if necessary
      - run:
          name: Build Java backend
          command: |
            cd BACKEND  # Change this to your backend directory if needed
            npm install
      
      - run:
          name: Install dependencies
          command: |
            cd apds7311OnlineBanking/BACKEND
            npm install

      # Run SonarCloud analysis
        - sonarcloud/scan:
          sonar_token: ${SONAR_TOKEN}
          project_key: "apds7311bank_apds7311OnlineBanking"
          organization: "apds7311bank"

workflows:
  build-and-scan:
    jobs:
      - build-and-analyze
