version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0  # SonarCloud orb

jobs:
  build-and-analyze:
    docker:
      - image: cimg/openjdk:17.0  # Using Java 17 for backend

    steps:
      - checkout  # Check out code

      # Build Java backend
      - run:
          name: Build Java backend
          command: |
            ./mvnw clean install

      # Run SonarCloud analysis
      - sonarcloud/scan

workflows:
  build-and-scan:
    jobs:
      - build-and-analyze

      # Run SonarCloud analysis
      - sonarcloud/scan

workflows:
  build-and-scan:
    jobs:
      - build-and-analyze
